name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/janesh64/custom-video-player-demo:latest
          docker push ghcr.io/janesh64/custom-video-player-demo:latest
